feat: Added support for django4.2
openedx/django-splash pull request #123
Opened 2023-05-20 14:11 UTC by awais786

2023-05-23 21:12 UTC, awais786 commented
https://docs.djangoproject.com/en/2.0/topics/http/middleware/#django.utils.deprecation.MiddlewareMixin

2023-06-01 11:40 UTC, UsamaSadiq commented on tox.ini
> -    django32: Django>=3.2,<4.0
We shouldn't remove `django32` yet.

2023-06-07 10:30 UTC, UsamaSadiq requested changes

2023-06-07 10:30 UTC, UsamaSadiq commented on .github/workflows/ci.yml
> +        toxenv: [quality, django32, django40, django42]
We should also update the coverage check to run against `django42` now to verify if that is also working perfectly or not.

2023-06-08 11:10 UTC, UsamaSadiq commented on CHANGELOG.rst
> -[1.2.0] - 2022-01-26
This line should also be kept in the CHANGELOG since it is the header for previous release.

2023-06-09 14:26 UTC, UsamaSadiq approved these changes

2023-06-12 13:16 UTC, merged